services:
  # Web Service
  - type: web
    name: wavedesk-twig
    env: php
    buildCommand: composer install --no-dev --optimize-autoloader
    startCommand: php -S 0.0.0.0:$PORT -t .
    envVars:
      - key: PHP_VERSION
        value: 8.2
      - key: DB_HOST
        fromDatabase:
          name: wavedesk-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: wavedesk-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: wavedesk-db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: wavedesk-db
          property: password

databases:
  # MySQL Database
  - name: wavedesk-db
    databaseName: wavedesk
    user: wavedesk_user